### ISSUE TITLE
Implement /models endpoint

### ISSUE THREAD

**Issue by jpwahle** [gipplab/cs-insights-prediction-endpoint#10]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
For data persistency, implement a storage route in NLP-Land-backend.

Endpoints to implement:
- [x] GET endpoint for retrieving a list of all models. 
- [x] POST endpoint for creating models.
- [x] PATCH/PUT endpoints for updating models. (Only for admins or creators of models).
- [x] DELETE endpoint for deleting models. (Only for admins).
- [x] Access control for PATCH/PUT and DELETE after issue #8
- [x] Use the schemas from #9.

**Describe alternatives you've considered**

**Additional context**

**Comment by tom-nslt** [comment]
```quote
> PATCH/PUT endpoints for updating models. (Only for admins or creators of models).
> DELETE endpoint for deleting models. (Only for admins).
```
Moved to #16
