### ISSUE TITLE
Design Docker orchestration for models (e.g., using Traefik)

### ISSUE THREAD

**Issue by jpwahle** [gipplab/cs-insights-prediction-endpoint#11]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
- [ ] Design adapters that should act as a connector of models and the main repository source code.
- [ ] Design model orchestration in Docker (and Traefik).

**Describe alternatives you've considered**

**Additional context**

**Comment by tom-nslt** [comment]
Closing. See https://github.com/gipplab/cs-insights-prediction-endpoint/issues/19#issuecomment-1214888946
