### ISSUE TITLE
Make use of the isActive field in the UserModel

### ISSUE THREAD

**Issue by tom-nslt** [gipplab/cs-insights-prediction-endpoint#14]
**Describe the solution you'd like**
When we are checking if a user is authenticated, we could add another dependency in the auth middleware. Dependency being a [fastapi dependency](https://fastapi.tiangolo.com/tutorial/dependencies/).
Currently the dependency chain checks the following way:
1. checks if token is available
2. check if token is valid and 
  * return user or 
  * return error

We can extend it to also check in third step if the user is active or not (the backend has to tell us this specific information). The new dependency flow would be as follows:
1. checks if token is available
2. check if token is valid parse user information
3. check if user is active
  * return user or 
  * return error

**Additional context**
https://github.com/ag-gipp/NLP-Land-prediction-endpoint/blob/96f164955b3581c6e91e012d8d5fcd1b31e82582/nlp_land_prediction_endpoint/models/model_user.py#L29

Can you please also open an issue for that and link this line of code of your commit in the issue?

_Originally posted by @jpelhaW in https://github.com/ag-gipp/NLP-Land-prediction-endpoint/pull/12#discussion_r771196074_

**Comment by jpwahle** [comment]
Thank's for including the issue :)
