### ISSUE TITLE
Model specific endpoints

### ISSUE THREAD

**Issue by tom-nslt** [gipplab/cs-insights-prediction-endpoint#16]
Implement endpoints which will be used for created Models

**Describe the solution you'd like**
The following routes need to be implemented
- [x] `GET, PATCH/PUT, UPDATE` **/models/{modelID}**
- [x] `POST(functionName, functionInput)`  **/models/{modelID}** 

https://github.com/ag-gipp/NLP-Land-prediction-endpoint/pull/15/files#diff-981a5534aba79e5fbd1688e070ba7e4c248fa8bcdb2b8dc7fd11ea3ad30fd03bR75-R82

**Comment by alexandertv** [comment]
In route_model.py:
Is there a better way to force the output in a dict?
`output = {req_function: str(output)}`

Solution:
`outputDict[req_function] = output`
